language: go
go:
- '1.10'

before_install:
- make dev-deps
- make deps
- make gen-swagger

script:
- make lint
- make run-test
- make bin/redirector-server-linux-amd64
- make bin/redirector-server-linux-arm
- make bin/redirector-server-linux-arm64
