package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// HostRules host rules
// swagger:model HostRules
type HostRules struct {

	// default target
	DefaultTarget Target `json:"defaultTarget,omitempty"`

	// host
	Host string `json:"host,omitempty"`

	// rules
	Rules []Rule `json:"rules"`
}

// Validate validates this host rules
func (m *HostRules) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HostRules) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HostRules) UnmarshalBinary(b []byte) error {
	var res HostRules
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
